# Rails内のものは変えようがないので除外
Metrics/CyclomaticComplexity:
  Exclude:
    - 'bin/*'
Metrics/MethodLength:
  Exclude:
    - 'bin/*'
    - 'db/**/*'
Metrics/PerceivedComplexity:
  Exclude:
    - 'bin/*'
Metrics/BlockLength:
  Exclude:
    - 'db/**/*'
Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
    - 'app/helpers/application_helper.rb'
    - 'app/helpers/test_helper.rb'
    - 'app/models/application_record.rb'
    - 'config/application.rb'
Style/SymbolProc:
  Exclude:
    - 'db/**/*'
Style/NumericLiterals:
  Exclude:
    - 'db/**/*'

AllCops:
  NewCops: enable

