# Rails内のものは変えようがないので除外
Metrics/CyclomaticComplexity:
  Exclude:
    - 'bin/*'
Metrics/MethodLength:
  Exclude:
    - 'bin/*'
    - 'db/**/*'
Metrics/PerceivedComplexity:
  Exclude:
    - 'bin/*'
Metrics/BlockLength:
  Exclude:
    - 'db/**/*'
Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
    - 'app/helpers/application_helper.rb'
    - 'app/helpers/test_helper.rb'
    - 'app/models/application_record.rb'
    - 'config/application.rb'
    - 'db/migrate/*'
Style/StringLiterals:
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/*'
Layout/EmptyLinesAroundBlockBody:
  Exclude:
    - 'db/schema.rb'
Metrics/MethodLength:
  Exclude:
    - 'db/migrate/*'
    - 'bin/bundle'
Style/FrozenStringLiteralComment:
  Exclude:
    - 'db/**/*'
Style/SymbolProc:
  Exclude:
    - 'db/**/*'
Style/NumericLiterals:
  Exclude:
    - 'db/**/*'
Metrics/AbcSize:
  Exclude:
    - 'db/migrate/*'
Layout/SpaceInsideArrayLiteralBrackets:
  Exclude:
    - 'db/migrate/*'
Style/SymbolArray:
  Exclude:
    - 'db/migrate/*'
Layout/LineLength:
  Exclude:
    - 'db/migrate/*'
    - db/schema.rb
Layout/SpaceInsidePercentLiteralDelimiters:
  Exclude:
    - 'db/migrate/*'
Style/WordArray:
  Exclude:
    - 'db/schema.rb'



AllCops:
  NewCops: enable

