# frozen_string_literal: true

# CreateUserProfileSubjects is a migration class generated by ActiveRecord
class CreateUserProfileSubjects < ActiveRecord::Migration[6.1]
  def change
    create_table :user_profile_subjects do |t|
      t.references :user_profile, foreign_key: true, null: false
      t.references :subject, foreign_key: true, null: false
      t.timestamps
    end
  end
end
