name: Static Analysis

on: pull_request

jobs:
  rubocop:
    name: Run rubocop
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup ruby
        uses: ruby/setup-ruby@v1

      - name: Run rubocop
        uses: reviewdog/action-rubocop@v1
        with:
          rubocop_version: 1.24.0
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          fail_on_error: true
